# 外观配置

[[plugins]]
repo = 'kaicataldo/material.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'SpaceVim/SpaceVim-theme'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'ajmwagar/vim-deus'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'sainnhe/everforest'

[[plugins]]
repo = 'mhartington/oceanic-next'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'glepnir/dashboard-nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# 彩虹括号
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

# 状态栏
[[plugins]]
repo = 'glepnir/galaxyline.nvim'

# tab栏
[[plugins]]
repo = 'romgrk/barbar.nvim'

[[plugins]]
repo = 'danilamihailov/beacon.nvim'
