# 代码配置 #

# lsp补全
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

# 代码提纲
[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
    let g:vista_default_executive = 'coc'
'''

# 代码重构
[[plugins]]
repo = 'brooth/far.vim'

# 格式化代码
[[plugins]]
repo = 'sbdchd/neoformat'

# 快速注释代码
[[plugins]]
repo = 'tpope/vim-commentary'

# 代码debug
[[plugins]]
repo = 'puremourning/vimspector'
