# dein命令
[[plugins]]
repo = 'haya14busa/dein-command.vim'

# which key
[[plugins]]
repo = 'liuchengxu/vim-which-key'

# sudo保存
[[plugins]]
repo = 'lambdalisue/suda.vim'
hook_add = '''
    let g:suda_smart_edit = 1
'''

# 自动匹配括号
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# jk加速
[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
    nmap j <Plug>(accelerated_jk_gj)
    nmap k <Plug>(accelerated_jk_gk)
'''

# Man 帮助手册
[[plugins]]
repo = 'vim-utils/vim-man'

# 命名
[[plugins]]
repo = 'voldikss/vim-codelf'
hook_add = '''
    let g:codelf_enable_popup_menu = v:true
'''

# 快速定位插件
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    nmap ss <Plug>(easymotion-s2)
'''

# 模糊搜索
[[plugins]]
repo = 'liuchengxu/vim-clap'
hook_post_update = '''
    call clap#installer#force_download()
'''

# 成对编辑
[[plugins]]
repo = 'tpope/vim-surround'

# 快速选中
[[plugins]]
repo = 'gcmt/wildfire.vim'

# 浮动终端
[[plugins]]
repo = 'voldikss/vim-floaterm'

# markdown
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = '''
sh -c "cd app && npm install"
'''

# 翻译
[[plugins]]
repo = 'voldikss/vim-translator'
