# git配置

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    let g:gitgutter_sign_priority=0
    let g:gitgutter_sign_added = '█'
    let g:gitgutter_sign_modified = '█'
    let g:gitgutter_sign_removed = '█'
    let g:gitgutter_sign_removed_first_line = '█'
    let g:gitgutter_sign_removed_above_and_below = '█'
    let g:gitgutter_sign_modified_removed = '█'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'junegunn/gv.vim'
