return {
  'olimorris/onedarkpro.nvim',
  lazy = true,
  opts = {
    colors = {
      dark = {
        telescope_prompt = "require('onedarkpro.helpers').darken('bg', 1, 'onedark')",
        telescope_results = "require('onedarkpro.helpers').darken('bg', 4, 'onedark')",
        telescope_preview = "require('onedarkpro.helpers').darken('bg', 6, 'onedark')",
        telescope_selection = "require('onedarkpro.helpers').darken('bg', 8, 'onedark')",
      },
      light = {
        telescope_prompt = "require('onedarkpro.helpers').darken('bg', 2, 'onelight')",
        telescope_results = "require('onedarkpro.helpers').darken('bg', 5, 'onelight')",
        telescope_preview = "require('onedarkpro.helpers').darken('bg', 7, 'onelight')",
        telescope_selection = "require('onedarkpro.helpers').darken('bg', 9, 'onelight')",
      },
    },
    highlights = {
      TelescopeBorder = { fg = '${telescope_results}', bg = '${telescope_results}' },
      TelescopePromptBorder = { fg = '${telescope_prompt}', bg = '${telescope_prompt}' },
      TelescopePromptCounter = { fg = '${fg}' },
      TelescopePromptNormal = { fg = '${fg}', bg = '${telescope_prompt}' },
      TelescopePromptPrefix = { fg = '${purple}', bg = '${telescope_prompt}' },
      TelescopePromptTitle = { fg = '${telescope_prompt}', bg = '${purple}' },
      TelescopePreviewTitle = { fg = '${telescope_results}', bg = '${green}' },
      TelescopeResultsTitle = { fg = '${telescope_results}', bg = '${telescope_results}' },
      TelescopeMatching = { fg = '${blue}' },
      TelescopeNormal = { bg = '${telescope_results}' },
      TelescopeSelection = { bg = '${telescope_selection}' },
      TelescopePreviewNormal = { bg = '${telescope_preview}' },
      TelescopePreviewBorder = { fg = '${telescope_preview}', bg = '${telescope_preview}' },
      NeoTreeTabActive = { fg = '${green}' },
      NeoTreeTabInactive = { fg = '${green}', bg = '${telescope_selection}' },
      NeoTreeTabSeparatorInactive = { fg = '${telescope_selection}', bg = '${telescope_selection}' },
      BufferCurrentWARN = { fg = '${yellow}', bg = 'NONE' },
      BufferCurrentERROR = { fg = '${red}', bg = 'NONE' },
    },
    styles = {
      types = 'NONE',
      methods = 'NONE',
      numbers = 'NONE',
      strings = 'NONE',
      comments = 'italic',
      keywords = 'bold,italic',
      constants = 'NONE',
      functions = 'bold',
      operators = 'NONE',
      variables = 'NONE',
      parameters = 'NONE',
      conditionals = 'NONE',
      virtual_text = 'NONE',
    },
    options = {
      highlight_inactive_windows = false,
    },
  },
}
